version = 3.7.17
runner.dialect = scala3

align = more
align.openParenDefnSite = true
danglingParentheses.preset = false
docstrings.style = SpaceAsterisk
maxColumn = 150

rewrite.rules = [RedundantParens, PreferCurlyFors, SortModifiers]

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true