include "application.conf"

feature-switch {
  version-1.enabled = true
}

microservice {
  services {
    auth {
      host = localhost
      port = ${wiremock.port}
    }

    insights-proxy {
      host       = localhost
      port       = ${wiremock.port}
      submit-url = "/check/insights"
    }
  }
}